vuesion/vuesion

README.md, package.json
=> add heroku app to readme

i18n/de.json, i18n/en.json, i18n/pt-BR.json, src/app/App.vue
Add the Brazilian Portuguese Translation 🇧🇷 
=> feat(i18n): add brazilian portuguese translations

package-lock.json, package.json, src/app/App.vue, src/app/actions.ts, src/app/app.ts, src/app/components/Components/Components.spec.ts, src/app/counter/Counter/Counter.spec.ts, src/app/getters.ts, src/app/home/Stage/Stage.spec.ts, src/app/index.template.html, src/app/mutations.ts, src/app/shared/plugins/i18n.spec.ts, src/app/shared/plugins/i18n.ts, src/app/store.ts, src/server/index.ts, src/server/isomorphic.ts, tools/tools.spec.ts
This PR will add a use case to render pages with the default language on the server, this information comes from the accept-language http header or from a user choice saved in a cookie (if the user uses the language switch) 
nope
closes #28
=> feat(i18n): set defaultLang from acceptLanguage or cookie

src/app/components/Components/Components.vue, src/app/shared/components/VueTooltip/VueTooltip.spec.ts, src/app/shared/components/VueTooltip/VueTooltip.vue
This PR will add a basic tooltip component
#20
=> feat(components): add tooltip

src/app/components/Components/Components.spec.ts, src/app/components/Components/Components.vue, src/app/shared/components/VueButton/VueButton.vue, src/app/shared/components/VueCheckBox/VueCheckBox.vue, src/app/shared/components/VueCollapse/VueCollapse.vue, src/app/shared/components/VueFooter/VueFooter.vue, src/app/shared/components/VueGrid/VueGrid.vue, src/app/shared/components/VueGridItem/VueGridItem.vue, src/app/shared/components/VueInput/VueInput.vue, src/app/shared/components/VueLoader/VueLoader.vue, src/app/shared/components/VueModal/VueModal.vue, src/app/shared/components/VueNavBar/VueNavBar.vue, src/app/shared/components/VuePanel/VuePanel.vue, src/app/shared/components/VuePanel/VuePanelBody/VuePanelBody.vue, src/app/shared/components/VuePanel/VuePanelFooter/VuePanelFooter.vue, src/app/shared/components/VuePanel/VuePanelHeader/VuePanelHeader.vue, src/app/shared/components/VueSlider/VueSlider.spec.ts, src/app/shared/components/VueSlider/VueSlider.vue, src/app/shared/components/VueSlider/algorithms.spec.ts, src/app/shared/components/VueSlider/algorithms.ts, src/app/shared/components/VueTabGroup/VueTabGroup.vue, src/app/shared/components/VueTabItem/VueTabItem.vue, src/app/shared/components/VueTooltip/VueTooltip.vue, src/app/shared/styles/_variables.scss, tools/generators/component/component.vue.hbs, tools/generators/connected/connected.vue.hbs
closes #16
This PR will add a basic RangeSlider component inspired by [airbnb/rheostat](https://github.com/airbnb/rheostat)
not that I know
#16
=> feat(components): add RangeSlider

.storybook/preview-head.html, src/app/shared/components/VueButton/VueButton.spec.ts, src/app/shared/components/VueButton/VueButton.stories.ts, src/app/shared/components/VueButton/VueButton.vue
possibility to add `icon` prop to `VueButton` component.
#66
=> Add font awesome icon support to the VueButton

src/app/shared/components/VueAccordion/VueAccordion.stories.ts, src/app/shared/components/VueButton/VueButton.stories.ts, src/app/shared/components/VueLoader/VueLoader.stories.ts, src/app/shared/components/VuePanel/VuePanel.stories.ts, tslint.json
=> Linting: trailing comma check

src/app/shared/components/VueMarkdown/VueMarkdown.spec.ts, src/app/shared/components/VueMarkdown/VueMarkdown.vue
=> fix(markdown-trim): render component with trimmed text

src/app/App.vue, src/app/components/Components/Components.vue, src/app/counter/Counter/Counter.vue, src/app/home/DevEx/DevEx.vue, src/app/home/EnterpriseReady/EnterpriseReady.vue, src/app/home/QuickStart/QuickStart.vue, src/app/home/UserExperience/UserExperience.vue, src/app/shared/components/VueFooter/VueFooter.vue, src/app/shared/components/VueGrid/VueGrid.stories.ts, src/app/shared/components/VueGrid/VueGrid.vue, src/app/shared/components/VueGridItem/VueGridItem.stories.ts, src/app/shared/components/VueGridRow/VueGridRow.spec.ts, src/app/shared/components/VueGridRow/VueGridRow.stories.ts, src/app/shared/components/VueGridRow/VueGridRow.vue, src/app/shared/components/VueNavBar/VueNavBar.vue, tools/generators/shared-component/component.spec.ts.hbs
=> feat(grid-row): added row to existing grid system

README.md, docs/I18N.md, docs/NPM_SCRIPTS.md, docs/VUEX.md
This will add some more documentation
nope
related to #35
=> chore: update docs

.gitignore, package-lock.json, package.json, src/app/shared/components/VueGridItem/VueGridItem.spec.ts, src/server/Logger.ts, src/server/dev-server.ts, src/server/index.ts
feat: add logging to express application
closes #93 
this PR will add a logger for everything that is server-side, with log rotation and so on.
not that I know
#93
=> feat: add logging to express application

.storybook/config.js, .storybook/preview-head.html, i18n/de-DE.json, i18n/en-US.json, i18n/pt-BR.json, src/app/components/Components/Components.spec.ts, src/app/components/Components/Components.vue, src/app/shared/components/VueAccordion/VueAccordion.stories.ts, src/app/shared/components/VueAutocomplete/IAutocompleteOption.ts, src/app/shared/components/VueAutocomplete/VueAutocomplete.spec.ts, src/app/shared/components/VueAutocomplete/VueAutocomplete.stories.ts, src/app/shared/components/VueAutocomplete/VueAutocomplete.vue, src/app/shared/components/VueAutocomplete/fixtures/IAutocompleteFixture.ts, src/app/shared/components/VueButton/VueButton.stories.ts, src/app/shared/components/VueInput/VueInput.vue, src/app/shared/components/VueLoader/VueLoader.stories.ts, src/app/shared/components/VuePanel/VuePanel.stories.ts, src/app/shared/styles/_variables.scss, src/app/shared/utils/misc.spec.ts, src/app/shared/utils/misc.ts
closes #58
This PR will add a autocomplete component + tests + story
think not
#58
=> feat(components): add vue-autocomplete

config/webpack.dev-server.config.js, package-lock.json, package.json, src/app/components/Components/Components.vue, src/app/shared/components/VueAutocomplete/VueAutocomplete.vue, src/client/index.ts, src/server/dev/server.ts, src/server/index.ts, src/server/isomorphic.ts, src/server/middlewares/index.ts, src/server/routes/AssetRoutes.ts, src/server/routes/PWARoutes.ts, src/server/routes/SSRRoutes.ts, src/server/utils/AppConfig.ts, src/server/utils/Logger.ts, src/server/utils/Utils.ts
closes #98
This PR will refactor the server application. instead of having a single file to manage everything, we now have separated route, utils and middleware files to keep it clean.
nope
#98
=> refactor(server): split up index.ts

src/client/index.ts, src/server/index.ts, src/server/routes/DemoRoutes.ts, src/server/routes/StaticRoutes.ts
closes #124
This PR will add client site error handling
I use the HttpService instead of vanilla JS, hopefully, this will work in every case.
#124
=> feat: add client site error logging

tools/generators/ast.ts
fixes #130
see title
nope
#130
=> fix(generators): change first parameter of registerModule to array

docs/guide/build.md, docs/guide/cli.md, docs/guide/vuex.md, docs/introduction.md, tools/generators/module/index.ts
Trying to improve language and spelling for clarity.
=> docs: improve wording

src/app/shared/services/HttpService.ts
An empty default value for the access token ensures that no authorization header is sent unless it is explicitely set.
No, discussed beforehand.
=> chore(http-service): remove default authorization header

.github/PULL_REQUEST_TEMPLATE.md, docs/.vuepress/config.js, docs/docs/style-guide.md, docs/guide/config.md, src/app/config/IAppConfig.ts, src/app/config/default.json, src/app/home/Home/Home.spec.ts, src/app/home/Home/Home.vue, src/app/home/Stage/Stage.spec.ts, src/app/home/Stage/Stage.vue, src/server/routes/SSRRoutes.ts, src/server/utils/RuntimeConfig.ts
closes #142
This PR will add a runtime configuration for e.g. feature flags + docs.
nope
#142
=> feat: add runtime config

i18n/de.json, i18n/en.json, i18n/pt.json, src/app/components/Components/Components.vue, src/app/shared/components/VueTruncate/VueTruncate.spec.ts, src/app/shared/components/VueTruncate/VueTruncate.stories.ts, src/app/shared/components/VueTruncate/VueTruncate.vue
closes #162
This PR adds a new component that truncates text and adds a link to expand the text. 
If the user expands the text it adds a link to collapse the text again.
nope
#162
=> feat(components): add text truncate component

src/app/components/Components/Components.vue, src/app/shared/components/VueCarousel/VueCarousel.spec.ts, src/app/shared/components/VueCarousel/VueCarousel.stories.ts, src/app/shared/components/VueCarousel/VueCarousel.vue, src/app/shared/styles/_variables.scss
closes #163
This PR adds a simple image carousel component
nope
#163
=> feat(components): add carousel

src/app/app.ts, src/app/shared/services/HttpService.ts
closes #164
see ticket #164 
nope
#164
=> refactor(http-service): set store from outside to prevent circular deps

package.json, src/app/components/Components/Components.vue, src/app/shared/components/VueToggle/VueToggle.spec.ts, src/app/shared/components/VueToggle/VueToggle.stories.ts, src/app/shared/components/VueToggle/VueToggle.vue, src/app/shared/styles/_variables.scss
closes #171 
This PR adds a new toggle component which is basically an alternative style of a checkbox
nope
#171
=> feat(components): add toggle

src/app/app/App/App.vue, src/app/app/actions.spec.ts, src/app/app/actions.ts, src/app/app/getters.spec.ts, src/app/app/getters.ts, src/app/app/mutations.spec.ts, src/app/app/mutations.ts, src/app/app/state.ts, src/app/shared/animations/FadeAnimation/FadeAnimation.spec.ts, src/app/shared/animations/FadeAnimation/FadeAnimation.vue, src/app/shared/components/VueCarousel/VueCarousel.vue, src/app/shared/components/VueCookieConsent/VueCookieConsent.spec.ts, src/app/shared/components/VueCookieConsent/VueCookieConsent.stories.ts, src/app/shared/components/VueCookieConsent/VueCookieConsent.vue, src/app/shared/styles/_variables.scss
closes #178
This PR adds a cookie component that will be shown to the user every time the consent version changes.
I refactored the fade transition from the carousel to be a re-usable component
#178
=> feat(components): add cookie consent

src/server/routes/SSRRoutes.ts
Simplifies error handling code for SSR routes a bit. E.g. `renderRedirect` is a misleading name as it does not necessarily redirect.
=> refactor(routes): simplify error-handling code

cypress/integration/404.spec.ts, src/server/isomorphic.ts
This PR will fix the 404 pages and adds an e2e test for it.
nope
no ticket
=> fix: proper 404 page

cypress/integration/redirect.spec.ts, src/app/app/routes.ts, src/app/router.ts, src/server/isomorphic.ts, src/server/routes/SSRRoutes.ts
If in a route guard the `next` callback is called with a
route argument, the app redirects to that route.
This change also adds an example auth guard so the behavior
can be tested.
No.
=> feat: redirect from route guards

docs/.vuepress/config.js, docs/zh-cn/docs/redirects.md
What is accomplished by your PR?
**Redirects.md translated.**
Is there something controversial in your PR?
**In the continuous improvement stage. So I will to pay attention to it.**
Thanks for contributing!
=> DOCS：Redirects.md translated

package.json
Furthermore, it enables yarn to work without failing
https://github.com/devCrossNet/vue-starter/issues/208
=> fix(package.json): update engines to match README (#208)

docs/.vuepress/config.js, docs/docs/prefetch-and-state-transfer.md
closes #210
This will add docs for prefetching data on the server
nope
#210
=> docs: add tutorial how to prefetch data on the server side

docs/.vuepress/config.js, docs/guide/third-party.md
related to #220
This PR will add a guide to integrate vuetify
nope
#220
=> docs: add guide to integrate with 3rd party UI libraries

docs/.vuepress/config.js, docs/docs/pwa.md
closes #226
This PR will add a new section for PWA in the docs
nope 
#226
=> docs: add progressive-web-app section

src/app/app/NotFound/NotFound.vue
Fixes English message on 404 page. "Site" is all pages together but here we just couldn't find one page.
No.
=> Improve 404 page wording

src/client/index.ts, src/server/isomorphic.ts
Catch unhandled errors in components' prefetch methods while routing on server and client side and log the error. Actual handling of the error(s) should be done in the prefetch method(s), likely writing some state to the store.
I guess error handling is always a bit controversial ;)
But this just unifies the server behavior with the client so should be fine.
=> catch errors for prefetch in a unified way

.all-contributorsrc, README.md
closes #232
This PR adds a reference to a bounty program and support for the [all contributors CLI](https://www.npmjs.com/package/all-contributors-cli)
nope
#232
=> docs(readme): add issue-hunt and all-contributors

cypress/integration/404.spec.ts, cypress/integration/redirect.spec.ts, src/app/app/routes.ts, src/server/isomorphic.ts, src/server/routes/SSRRoutes.ts
Do not change the current route if page is not found.
Looking into the error case (500), too, but this should be good as an isolated improvement.
I don't think so.
#193
=> Don't change route on 404

src/app/shared/components/VueSelect/VueSelect.spec.ts
closes #236
This PR adds a missing test to the vue-select test suite
nope
#236
=>  test(vue-select): add test for disabled component

src/app/counter/Counter/Counter.spec.ts, tools/generators/connected/connected.spec.ts.hbs
closes #242
This PR improves the test set up for connected components. I discovered that the test set up in the current blueprints are not really scalable.
nope
#242
=> refactor(tests): improve test setup for connected components

src/app/shared/components/VueTooltip/VueTooltip.spec.ts, src/app/shared/components/VueTooltip/VueTooltip.stories.ts, src/app/shared/components/VueTooltip/VueTooltip.vue
closes #254
This PR adds a new property `disabled` to the tooltip component which allows us to suppress the tooltip programmatically
nope
#254
=> feat(vue-tooltip): add property to programmatically suppress tooltip

config/webpack.client.config.js, src/app/shared/components/VueInput/VueInput.spec.ts, src/app/shared/components/VueInput/VueInput.stories.ts, src/app/shared/components/VueInput/VueInput.vue, src/app/shared/styles/global.scss
This PR will:
- add a webpack performance budget
- remove the empty alt tag rule from CSS because it's a valid behavior
- add a new property `autofocus` to the vue-input component
I solved multiple tickets in this PW
#250 
#257 
#260
=> 1.4.0 tickets

config/webpack.client.config.js, src/app/shared/components/VueDropdownMenu/VueDropdownMenu.spec.ts, src/app/shared/components/VueDropdownMenu/VueDropdownMenu.stories.ts, src/app/shared/components/VueDropdownMenu/VueDropdownMenu.vue, src/app/shared/styles/_variables.scss, src/app/shared/styles/variables/_dropdown-menu.scss
closes #249
This PR adds a new component `vue-dropdown-menu`.
I changed something for the performance budgets, will fix it in the next branch asap.
#249
=> feat(components): add dropdown menu

docs/guide/clean-up.md, docs/zh-cn/guide/clean-up.md, package-lock.json, src/app/counter/Counter/Counter.vue, src/app/state.ts, src/app/store.ts, tools/generators/ast.ts, tools/generators/connected/connected.vue.hbs, tools/generators/module/index.ts, tools/generators/module/module.ts.hbs
closes #151
This PR will add lazy loading for vuex modules. I remove all of the AST functions for store.ts and state.ts that are not needed anymore and add a helper function to register modules in connected components on the store.
nope
#151
=> feat: load vuex-modules on demand

.github/PULL_REQUEST_TEMPLATE.md, .storybook/preview-head.html, package.json, src/app/app/Error/Error.vue, src/app/app/NotFound/NotFound.vue, src/app/counter/Counter/Counter.vue, src/app/form/Form/Form.vue, src/app/home/DevEx/DevEx.vue, src/app/home/EnterpriseReady/EnterpriseReady.vue, src/app/home/QuickStart/QuickStart.vue, src/app/home/Stage/Stage.vue, src/app/home/UserExperience/UserExperience.vue, src/app/shared/components/VueCalendar/VueCalendar.vue, src/app/shared/components/VueHeadline/VueHeadline.spec.ts, src/app/shared/components/VueHeadline/VueHeadline.stories.ts, src/app/shared/components/VueHeadline/VueHeadline.vue, src/app/shared/styles/typo.scss, src/app/store.ts, tools/generators/component/component.vue.hbs, tools/generators/connected/connected.vue.hbs
This PR will add a new component for headlines. This will ensure to stick to the design system typography
replaced all headline with the component
no ticket
=> feat(components): add headline component

.storybook/config.js, src/app/shared/components/VueDonutChart/IChartDataItem.ts, src/app/shared/components/VueDonutChart/VueDonutChart.spec.ts, src/app/shared/components/VueDonutChart/VueDonutChart.stories.ts, src/app/shared/components/VueDonutChart/VueDonutChart.vue, src/app/shared/components/icons/Icons.stories.ts, src/app/shared/styles/DesignSystem.stories.ts, tools/generators/component/component.spec.ts.hbs, tools/generators/component/component.vue.hbs, tools/generators/component/index.ts
This PR is a spike for a donut/pie chart solution with SVG and CSS only. it's not using the canvas and is accessible
I was not able to figure out a solution to display tooltips so I created a legend on the right side
no ticket
=> feat(components): add donut chart

src/app/shared/components/VueDropdownMenu/VueDropdownMenu.spec.ts, src/app/shared/components/VueDropdownMenu/VueDropdownMenu.stories.ts, src/app/shared/components/VueDropdownMenu/VueDropdownMenu.vue
This PR adds the possibility to pass a `separator` option to the dropdown menu
nope
no ticket
=> feat(vue-dropdown-menu): add separator option

src/app/shared/components/VueTabGroup/VueTabGroup.vue
related to #259
this PR makes the tab component accessible for the keyboard
it was @livgrhm idea. I couldn't wait to implement it, sorry 😞  
no ticket
=> feat(vue-tab-group): add keyboard accessibility

i18n/de.json, i18n/en.json, i18n/pt.json, i18n/zh-cn.json, src/app/shared/components/VueAccordion/VueAccordionItem/VueAccordionItem.vue, src/app/shared/components/VueCalendar/VueCalendar.spec.ts, src/app/shared/components/VueCalendar/VueCalendar.vue, src/app/shared/components/VueCookieConsent/VueCookieConsent.vue, src/app/shared/components/VueTabGroup/VueTabGroup.vue, src/app/shared/plugins/i18n/i18n.ts, src/app/shared/styles/variables/_calendar.scss
closes #259
This PR adds a lot of tabindexs, aria-labels and keyboard events to several components.
nope
#259
=> feat(components): accessibility iteration

package-lock.json, src/app/app.ts, src/app/form/FormExample/FormExample.spec.ts, src/app/form/FormExample/FormExample.vue, src/vue.plugins.d.ts
related to #292, related to #291
This PR adds a test for the form example to showcase how to test form validation and I remove one unnecessary type hint `$refs`
I was able to resolve the typing issue mentioned in #291 `validator: 'new' as 'new',` weird type-script behavior
#291 
#292
=> test: add example for form validation

.prettierrc, config/webpack.base.config.js
fixes #306
This PR removes the auto-fix rule in ForkTsCheckerWebpackPlugin for tslint in order to get rid of the behaviour described in #306 
#306
=> fix(tslint): remove tslint autofix

src/app/counter/Counter/Counter.vue, src/app/form/FormExample/FormExample.vue, src/app/shared/components/VueAutocomplete/VueAutocomplete.vue, src/app/shared/components/VueBadge/VueBadge.spec.ts, src/app/shared/components/VueBadge/VueBadge.stories.ts, src/app/shared/components/VueBadge/VueBadge.vue, src/app/shared/components/VueButton/VueButton.spec.ts, src/app/shared/components/VueButton/VueButton.stories.ts, src/app/shared/components/VueButton/VueButton.vue, src/app/shared/components/VueCalendar/VueCalendar.vue, src/app/shared/components/VueCard/VueCard.stories.ts, src/app/shared/components/VueCollapse/VueCollapse.stories.ts, src/app/shared/components/VueInput/VueInput.stories.ts, src/app/shared/components/VueLoader/VueLoader.spec.ts, src/app/shared/components/VueLoader/VueLoader.stories.ts, src/app/shared/components/VueLoader/VueLoader.vue, src/app/shared/components/VueModal/VueModal.stories.ts, src/app/shared/components/VueNotificationStack/VueNotificationStack.stories.ts, tools/generators/connected/connected.vue.hbs
closes #303
This PR replaces the variant flags with a variant string for vue-button, vue-badge and vue-loader.
I named the prop `variant` is that ok?
#303
=> refactor(components): use color enum instead of variant flags

docs/docs/style-guide.md, docs/guide/cli.md, docs/zh-cn/docs/style-guide.md, docs/zh-cn/guide/cli.md
=> update  command  *npm run g* -> *npm run generate*

package-lock.json, package.json
This PR updates the vue-starter-service version which provides now a parallel task. I changed the pre-commit and ci scripts to use the parallel command which speeds things up.
nope
no issue
=> chore: optimize npm scripts

.vue-starter/generators/connected/connected.vue.hbs, .vue-starter/generators/module/actions.spec.ts.hbs, .vue-starter/generators/module/actions.ts.hbs, src/app/counter/Counter/Counter.spec.ts, src/app/counter/Counter/Counter.vue, src/app/counter/actions.spec.ts, src/app/counter/actions.ts, src/app/counter/module.ts, src/app/shared/plugins/i18n/i18n.spec.ts, src/app/shared/plugins/i18n/i18n.ts, src/app/shared/services/HttpService/setupRequestInterceptor.spec.ts, src/app/shared/services/HttpService/setupResponseInterceptor.spec.ts, src/client/index.ts, src/server/isomorphic.ts
closes #336
This PR replaces **almost** all promises with async/await. why? it's better to read and forces better error handling via try/catch
I touched some code in the isomorphic file which was not super easy to refactor to async/await, would be nice if someone could test it before I merge this commit.
#336
=> refactor: change promises to async/await

.vue-starter/storybook/addons.js, .vue-starter/storybook/config.js, package-lock.json, package.json
This PR adds an addon to storybook which allows designing components for different viewports
nope
no ticket
=>  feat(storybook): add viewport addon

package-lock.json, package.json, src/app/shared/components/VueDataTable/VueDataTable.stories.ts, src/app/shared/components/VueDropdownMenu/VueDropdownMenu.stories.ts, src/server/isomorphic.ts
closes #338
This PR enables the vue-starter to use the new features of vue version 2.6. 
I still like the prefetch pattern more than the serverPrefetch one because it unifies the client/server logic.
what do you think?
#338
=> feat: upgrade to vue 2.6

package-lock.json, package.json, src/app/store.ts, tsconfig.test.json
This PR updates the dependencies and getting rid of the ts-jest version lock.
I did not update vee-validate and vue-test-utils because they have some breaking changes. I also removed the LocalStorage adapter example because we don't use it anyway and we also not recommend using it.
no ticket
=> chore: update dependencies

src/app/app/App/App.vue, src/app/shared/plugins/i18n/i18n.ts
closes #353
This PR fixes the issue described in #353 
nope
#353
=> fix(i18n): handle cached locales in client correctly

.vuesion/storybook/config.js, src/app/app.ts, src/app/shared/designSystem/docs/DesignSystem.stories.ts, src/app/shared/designSystem/global.scss, src/app/shared/directives/Directives.stories.ts, src/app/shared/directives/index.ts, src/app/shared/directives/sr-only.ts
This PR adds a directive to hide content that is only necessary for screen readers.
nope
no ticket
=> feat(directives): add v-sr-only

src/app/shared/animations/CollapseAnimation/CollapseAnimation.spec.ts, src/app/shared/animations/CollapseAnimation/CollapseAnimation.vue
closes #360
This PR removes the magic number `32` from the collapse animation, for more context see #360 
nope
#360
=> refactor(vue-collapse): remove magic number

src/app/shared/components/VueButton/VueButton.spec.ts, src/app/shared/components/VueButton/VueButton.stories.ts, src/app/shared/components/VueButton/VueButton.vue, src/app/shared/components/VueCookieConsent/VueCookieConsent.vue, src/app/shared/components/utils.ts, src/app/shared/designSystem/variables/_button.scss
changes static button variations to dynamic ones
nope
no ticket
=> refactor(vue-button): add dynamic variations

src/app/shared/components/VueBadge/VueBadge.spec.ts, src/app/shared/components/VueBadge/VueBadge.stories.ts, src/app/shared/components/VueBadge/VueBadge.vue, src/app/shared/designSystem/variables/_badge.scss
This PR replaces the hardcoded badge variations with dynamic ones
nope
no ticket
=> refactor(vue-badge): add dynamic variations

src/app/shared/components/VueLoader/VueLoader.spec.ts, src/app/shared/components/VueLoader/VueLoader.stories.ts, src/app/shared/components/VueLoader/VueLoader.vue, src/app/shared/designSystem/variables/_loader.scss
This PR replaces the hardcoded loader variations with dynamic ones
nope
no ticket
=> refactor(vue-loader): add dynamic variations

src/app/shared/components/VueModal/VueModal.vue, src/app/shared/designSystem/variables/_modal.scss, src/app/shared/modules/auth/LoginForm/LoginForm.vue
This PR removed the minwidth from the modal so that it always fits the content
nope
no ticket
=> fix(vue-modal): remove min-width

src/app/shared/components/VueDropdownMenu/VueDropdownMenu.vue, src/app/shared/components/VueSidebar/VueSidebar.vue, src/app/shared/designSystem/global.scss, src/app/shared/designSystem/variables/_dropdown-menu.scss, src/app/shared/designSystem/variables/_sidebar.scss
This PR sets the height of the sidebar to 100% and removes the gap to the navbar. I will work on different page templates to provide examples for a different behaviour
nope
no ticket
=> fix(vue-sidebar): remove gap to the navbar

.vuesion/storybook/config.js, .vuesion/storybook/theme.js, .vuesion/storybook/webpack.config.js, package-lock.json, package.json
The 5.0.4 version of storybook brings some useful new features:
1. New design
2. New canvas toolbar to give quick visual access to addons
3. overhauled navigation sidebar with a better menu
In the side panel of storybook, hierarchies of story clusters is not maintained
the fix will close the issue --> https://github.com/devCrossNet/vue-starter/issues/369
description...
=> feat(storybook): update storybook

.circleci/config.yml, src/app/shared/components/VueAutocomplete/VueAutocomplete.vue, src/app/shared/components/VueButton/VueButton.vue, src/app/shared/components/VueCalendar/VueCalendar.vue, src/app/shared/components/VueCard/VueCard.stories.ts, src/app/shared/components/VueDataTable/VueDataTable.stories.ts, src/app/shared/components/VueDataTable/VueDataTable.vue, src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.vue, src/app/shared/components/VueDonutChart/VueDonutChart.vue, src/app/shared/components/icons/Icons.stories.ts, src/app/shared/designSystem/docs/components/ColorPalette.vue, src/app/shared/designSystem/docs/components/IconList.vue, src/app/shared/designSystem/variables/_accordion.scss, src/app/shared/designSystem/variables/_autocomplete.scss, src/app/shared/designSystem/variables/_brand.scss, src/app/shared/designSystem/variables/_button.scss, src/app/shared/designSystem/variables/_calendar.scss, src/app/shared/designSystem/variables/_color-palette.scss, src/app/shared/designSystem/variables/_data-table.scss, src/app/shared/modules/auth/LoginForm/LoginForm.vue
This PR changes the color palette and makes all components color accessible
nope
no ticket
=> refactor: accessibility iteration

src/app/shared/components/VueBreadcrumb/VueBreadcrumb.vue, src/app/shared/components/VueButton/VueButton.spec.ts, src/app/shared/components/VueCalendar/VueCalendar.vue, src/app/shared/components/VueDataTable/VueDataTable.vue, src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.vue, src/app/shared/components/VueDonutChart/VueDonutChart.vue, src/app/shared/components/VueSelect/VueSelect.vue
closes #387
This PR adds a `:key` property to all `v-for` directives and it removes the `v-if` directives from nodes that already have `v-for`
nope. @MohitTilwani15 - please review
#387
=> refactor: apply best practices for v-for and v-if

src/app/shared/designSystem/docs/DesignSystem.stories.ts
Replace broken link in "Design System" Story.
I was unable to check whether the link works now, since I am unable to access any of the docs when I `npm run dev` locally. Unfortunately I don't have the time to dig deeper into this right now.
I decided to create the pull request anyways, since I'm confident I didn't brake anything with my change :)
#394
=> docs: fix link to 3rd party UI libs tutorial

.vuesion/generators/component/component.spec.ts.hbs, .vuesion/generators/component/component.stories.ts.hbs, .vuesion/generators/connected/connected.spec.ts.hbs, .vuesion/generators/connected/connected.vue.hbs, .vuesion/generators/module/getters.spec.ts.hbs, .vuesion/generators/module/module.ts.hbs, .vuesion/generators/module/mutations.spec.ts.hbs, .vuesion/generators/module/mutations.ts.hbs, .vuesion/generators/module/routes.ts.hbs, .vuesion/generators/module/state.ts.hbs, package-lock.json, package.json
closes #404, closes #408
This PR uses kebabCase in the storybook template and it adds conditionals to the connected and module templates for the case that users don't want to have vuex in their module.
I needed to change something in the service so I updated the service version
- #404 
- #408
=> fix(generators): implement conditionals, fix kebabCase

package.json, src/app/shared/components/VueMarkdown/VueMarkdown.spec.ts, src/app/shared/components/VueMarkdown/VueMarkdown.vue, src/app/shared/designSystem/docs/DesignSystem.stories.ts
closes #394
This PR adds a new prop to the markdown component which configures if the links behave like native links or the router-link
nope
#394
=> feat(vue-markdown): prop for using router or native links

src/app/shared/components/VueTextarea/VueTextarea.spec.ts, src/app/shared/components/VueTextarea/VueTextarea.stories.ts, src/app/shared/components/VueTextarea/VueTextarea.vue
closes #435
This PR adds a new component for the input type textarea
pretty much copy and paste from the input component for now
#435
=> feat(components): add textarea

src/app/form/Form/Form.vue, src/app/form/FormExample/FormExample.vue, src/app/shared/components/VueSelect/VueSelect.spec.ts, src/app/shared/components/VueSelect/VueSelect.vue, src/app/shared/designSystem/variables/_select.scss
closes #438
This PR changes the styling of the vue-select component to match the styling of the input type text element
nope
#438
=> feat(vue-select): add label

src/app/shared/components/VueDataTable/DataTableFixtures.ts, src/app/shared/components/VueDataTable/IDataTable.ts, src/app/shared/components/VueDataTable/VueDataTable.spec.ts, src/app/shared/components/VueDataTable/VueDataTable.stories.ts, src/app/shared/components/VueDataTable/VueDataTable.vue, src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.vue
closes #439
This PR adds a new property to IDatatableHeader which allows adding a custom CSS class for every column.
I also changed the maxRows logic to less than 0 instead of 0
#439
=> fix(vue-data-table): add custom css class property

src/app/shared/components/VueAutocomplete/VueAutocomplete.spec.ts, src/app/shared/components/VueAutocomplete/VueAutocomplete.stories.ts, src/app/shared/components/VueAutocomplete/VueAutocomplete.vue, src/app/shared/designSystem/variables/_autocomplete.scss
closes #447
see title
nope
#447
=> feat(vue-autocomplete): add autofocus and validation

.vuesion/generators/connected/connected.spec.ts.hbs, src/app/counter/Counter/Counter.spec.ts, src/app/home/Home/Home.spec.ts, src/app/shared/components/VueAutocomplete/VueAutocomplete.vue
This PR simplifies the test set-up for connected components
nope, only less code
no ticket
=> test: simplify tests for connected components

src/app/shared/components/VueAutocomplete/VueAutocomplete.stories.ts, src/app/shared/components/VueAutocomplete/VueAutocomplete.vue, src/app/shared/components/VueAutocomplete/fixtures/IAutocompleteFixture.ts
closes #449
This PR adds v-model support to the autocomplete component
nope
#449
=> feat(vue-autocomplete): add v-model support

src/app/shared/components/VueInput/VueInput.vue, src/app/shared/components/VueSelect/VueSelect.vue, src/app/shared/components/VueTextarea/VueTextarea.vue
fixes #453
This PR fixes a long-existing bug with duplicate event handlers on the following components:
- vue-select
- vue-input
- vue-textarea
nope
#453
=> fix(components): remove duplicate event handlers

.vuesion/generators/crud-module/mutations.ts.hbs
=> fix(generators): make delete mutation reactive

package-lock.json, package.json, src/app/shared/components/VueBadge/VueBadge.spec.ts
closes #430
This PR adds the `@testing-library/vue` for writing better maintainable tests. I also added an example. The rest of the tests will be migrated with the component rewrite.
It does not add RITEway because the proposed library for jest doesn't seem to very well maintained
#430
=> test: add @testing-library/vue for better testing

package-lock.json, package.json, src/app/app.ts, src/app/example/form/FormExample/FormExample.spec.ts, src/app/shared/components/VueAccordion/VueAccordionItem/VueAccordionItem.spec.ts, src/app/shared/components/VueAutocomplete/VueAutocomplete.spec.ts, src/app/shared/components/VueButton/VueButton.spec.ts, src/app/shared/components/VueCalendar/VueCalendar.spec.ts, src/app/shared/components/VueCheckbox/VueCheckbox.spec.ts, src/app/shared/components/VueCollapse/VueCollapse.spec.ts, src/app/shared/components/VueCookieConsent/VueCookieConsent.spec.ts, src/app/shared/components/VueDataTable/VueDataTable.spec.ts, src/app/shared/components/VueDatePicker/VueDatePicker.spec.ts, src/app/shared/components/VueDropdownMenu/VueDropdownMenu.spec.ts, src/app/shared/components/VueInput/VueInput.spec.ts, src/app/shared/components/VueInput/VueInput.vue, src/app/shared/components/VueMarkdown/VueMarkdown.spec.ts, src/app/shared/components/VueModal/VueModal.spec.ts, src/app/shared/components/VuePagination/VuePagination.spec.ts, src/app/shared/components/VueSelect/VueSelect.vue, src/app/shared/components/VueSidebar/VueSidebar.spec.ts, src/app/shared/components/VueStarRating/VueStarRating.spec.ts, src/app/shared/components/VueTabGroup/VueTabGroup.spec.ts, src/app/shared/components/VueTabGroup/VueTabItem/VueTabItem.spec.ts, src/app/shared/components/VueTextarea/VueTextarea.spec.ts, src/app/shared/components/VueTextarea/VueTextarea.vue, src/app/shared/components/VueToggle/VueToggle.spec.ts, src/app/shared/components/VueTooltip/VueTooltip.spec.ts, src/app/shared/modules/auth/LoginForm/LoginForm.spec.ts
Fix memory leak caused by old version of vee-validate.
(Less big if a change as the attempt to update to v3 (#523))
* Haven't tried updating to latest v2 (2.2)
* Might need some more manual testing for all validation cases...
=> fix memory leak caused by vee-validate

.vuesion/generators/connected/connected.spec.ts.hbs, src/app/example/counter/Counter/Counter.spec.ts
State type of the global store is wrong (uses module's state type) and this fixes it.
Concerns counter example and connected generator template.
Not expected.
=> fix: fix state type in connected component tests

src/components/atoms/VueInput/VueInput.vue, src/components/atoms/VueToggle/VueToggle.vue
=> fix(components): use id as labels for-attribute value

src/components/atoms/VueSelect/VueSelect.spec.ts, src/components/atoms/VueSelect/VueSelect.stories.ts, src/components/atoms/VueSelect/VueSelect.vue
closes #530
This PR fixes an issue with updating the values of vue-select manually
nope
#530
=> fix(vue-select): use computed instead of ref for watching v-model

src/assets/designSystem/components/atoms/_slider.scss, src/components/atoms/VueSlider/VueSlider.spec.ts, src/components/atoms/VueSlider/VueSlider.stories.ts, src/components/atoms/VueSlider/VueSlider.vue
closes #526
see #526 
I added a todo to retrieve the handeSize dynamically together with the re-design of the slider
#526
=> fix(vue-slider): use parseFloat instead of parseInt

src/components/molecules/VueCard/VueCardHeader/VueCardHeader.vue, src/components/organisms/Stage/Stage.vue, src/components/organisms/VueFooter/VueFooter.vue, src/pages/example/counter.vue, src/pages/example/dashboard.vue, src/pages/index.vue
This PR removes unused props *with-vertical-space* and *fill* passed on to _vue-grid_
-
-
=> fix: remove unused prop with-vertical-space

src/components/atoms/VueText/VueText.spec.ts, src/components/atoms/VueText/VueText.stories.ts, src/components/atoms/VueText/VueText.vue, src/components/layout/VueBox/VueBox.stories.ts, src/components/layout/VueBox/VueBox.vue, src/components/layout/VueColumns/VueColumn/VueColumn.vue, src/components/layout/VueColumns/VueColumns.spec.ts, src/components/layout/VueColumns/VueColumns.stories.ts, src/components/layout/VueColumns/VueColumns.vue, src/components/layout/VueInline/VueInline.spec.ts, src/components/layout/VueInline/VueInline.stories.ts, src/components/layout/VueInline/VueInline.vue, src/components/layout/VueStack/VueStack.vue, src/components/layout/VueTiles/VueTiles.vue, src/components/prop-validators.spec.ts, src/components/prop-validators.ts, src/components/utils.spec.ts, src/components/utils.ts
This Pr improves the layout components
nope
no ticket
=> Improve layout components

nuxt.config.ts, package-lock.json, package.json, tsconfig.json
This Pr adds logging with nuxt-winston-log
nope
no ticket
=> feat: add logging with winston

nuxt.config.ts, src/custom-typings.d.ts, src/plugins/pwa/update.client.ts
This Pr adds a plugin that checks for PWA updates and reloads the page
nope
closes #542
=> feat: add pwa update script

.eslintignore, .gitignore, .prettierignore, .vuesion/config.json, package-lock.json, package.json, tsconfig.json
This PR adds a script that generates type definition from remote swagger schemas
nope
no ticket
=> feat: add type-gen for swagger

cypress/integration/apollo.spec.ts, src/pages/example/apollo.vue, src/pages/example/counter.vue
=> test(e2e): add test for apollo

README.md, src/components/layout/VueColumns/VueColumn/VueColumn.spec.ts, src/components/layout/VueColumns/VueColumn/VueColumn.vue, src/components/layout/VueColumns/VueColumns.spec.ts, src/components/layout/VueColumns/VueColumns.stories.ts, src/components/layout/VueColumns/VueColumns.vue, src/components/layout/VueInline/VueInline.spec.ts, src/components/layout/VueInline/VueInline.vue, src/plugins/vue-i18n/vue-i18n.ts
- feat(i18n): add formatFallbackMessages
- feat(vue-column): add align-y prop
- feat(vue-columns): add full-page prop
- fix(vue-inline): interpolate revert prop 
nope
no ticket
=> improvements

.circleci/config.yml
=> ci: checkout and deploy premium component repo

i18n/de.json, i18n/en.json, src/components/marketing/LearnMore/LearnMore.vue, src/pages/download.spec.ts, src/pages/download.vue
adds a download page with the vuesion themes
nope
no ticket
=> feat: add download page

README.md
Correct **CONTRIBUTING.md** path in **README.md**
No
No
=> docs(README.md): correct CONTRIBUTING.md path

src/composables/README.md
This PR fixes a tiny grammar typo.
=> docs(README.md): fix grammar typo

src/composables/use-prefill-store-action.ts, src/plugins/icons.ts, src/plugins/vee-validate.ts, src/utils/fetchWithCookies.ts
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
should be straightforward
=> fix: import nuxt composables from #imports
