vuesion/vuesion

package-lock.json
package.json
src/app/app.ts
src/app/counter/Counter/Counter.vue
src/app/counter/mutations.ts
src/app/home/actions.ts
src/app/shared/plugins/vuex/PersistCookieStorage.spec.ts
src/app/shared/plugins/vuex/PersistCookieStorage.ts
src/app/shared/plugins/vuex/PersistLocalStorage.spec.ts
src/app/shared/plugins/vuex/PersistLocalStorage.ts
src/app/shared/plugins/vuex/vuex-persist.spec.ts
src/app/shared/plugins/vuex/vuex-persist.ts
src/app/store.ts
src/client/index.ts
src/server/index.ts
src/server/isomorphic.ts

this PR will add a new VueX plugin to persist state. It'll also add two implementation to persist state, one is the `PersistLocalStorage` and one is `PersistCookieStorage`.
example code *store.ts*:
```
export const getStore = (serverContext?: IServerContext): Store<any> => {
const persistCookieStorage: PersistCookieStorage = new PersistCookieStorage(['counter']);
if (serverContext) {
state = persistCookieStorage.getMergedStateFromServerContext(serverContext, state);
}
return new Vuex.Store({
state,
actions,
mutations,
getters,
plugins: [VuexPersist([
new PersistLocalStorage(['home']),
persistCookieStorage,
])],
});
};
```
nope
#25

feat(vuex): add vuex-persist + LocalStorage and Cookie persister

---

src/app/router.ts

Allow router to handle anchors e.g `/foo#bar` 
Fixed with #64

Allow vue-router to handle anchors

---

src/app/App.vue
src/app/shared/components/VueNavBar/VueNavBar.spec.ts
src/app/shared/components/VueNavBar/VueNavBar.vue

Closes the nav bar automatically once an item in is clicked.
I'm using a global event bus, because the VueNavBar and the items in it are in disparate components and they need a way to talk to eachother. This doesn't feel like the best way to me, but I'm a VueJS beginner, so I would love to learn the better way!
I have added a test, but it does not work. I can't find the element to click on to test it. Perhaps this cannot be unit tested, because it is implemented across components? Any insight into how to approach this is appreciated!

feat(navbar): automatically close nav bar when item is clicked

---

i18n/de.json
i18n/en.json
i18n/pt.json
src/app/components/Components/Components.spec.ts
src/app/components/Components/Components.vue
src/app/shared/components/VueDataTable/DataTableFixtures.ts
src/app/shared/components/VueDataTable/IDataTable.ts
src/app/shared/components/VueDataTable/VueDataTable.spec.ts
src/app/shared/components/VueDataTable/VueDataTable.stories.ts
src/app/shared/components/VueDataTable/VueDataTable.vue
src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.spec.ts
src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.vue
src/app/shared/components/VueDataTable/VueDataTableRow/VueDataTableRow.spec.ts
src/app/shared/components/VueDataTable/VueDataTableRow/VueDataTableRow.vue
src/app/shared/components/VueDataTable/VueDataTableSearch/VueDataTableSearch.spec.ts
src/app/shared/components/VueDataTable/VueDataTableSearch/VueDataTableSearch.vue

closes #141
This PR adds a new DataTable component which includes following features:
- define column schema (not-displaying certain columns, rename titles, rearrange appearance)
- display JSON as table
- sorting of rows, one column at a time
- filtering
- pagination
- server-side-rendering
nope
#141

feat(components): add data-table

---

docs/guide/cli.md

closes #155
This PR adds a hint for using a path in the name option of the generator cli
nope
#155

docs(cli): add hint for paths in names

---

package.json
src/app/shared/components/VueModal/VueModal.vue

fixes #203
This PR fixes the modal dialog for Firefox, the solution is to use the `mousedown` event instead of the `click` event. It seems that Firefox emits events in a different order than other browsers.
I also removed the SPA build from the CI task to save some time in the pipeline
#203

fix(vue-modal): change overlay event listener for Firefox

---

Dockerfile
docs/.vuepress/config.js
docs/guide/docker.md

Dockerfile now successfully builds image
What do you think about the difference in the port? 3000 and 3001 are chosen so both docker and dev can be up in parallel. That creates a "false" message in the console when starting docker:
```shell
info: node server started at http://localhost:3000
```
Which is documented but nevertheless not ideal
#214 
- [x ] Run unit tests to ensure all existing tests are still passing
- [x ] Add new documentation for the code introduced by your PR

fix: dockerfile now builds image (Fixes #214)

---

src/app/components/Components/Components.vue
src/app/shared/components/VueTabGroup/VueTabGroup.spec.ts
src/app/shared/components/VueTabGroup/VueTabGroup.stories.ts
src/app/shared/components/VueTabGroup/VueTabGroup.vue
src/app/shared/components/VueTabGroup/VueTabItem/VueTabItem.vue

closes #245 
This PR adds a new property `is-active` to the `vue-tab-item` component. This enables us to pre-select a tab
nope
#245

feat(vue-tab-group): add is-active property to pre-select tab-item

---

src/app/components/Components/Components.spec.ts
src/app/components/Components/Components.vue
src/app/shared/components/VueDataTable/DataTableFixtures.ts
src/app/shared/components/VueDataTable/IDataTable.ts
src/app/shared/components/VueDataTable/VueDataTable.stories.ts
src/app/shared/components/VueDataTable/VueDataTable.vue
src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.spec.ts
src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.vue

closes #251, closes #252
This PR will add the whole row to the scoped slot which enables users to have access to the row data inside a custom cell renderer.
it also adds two new properties to the column definition, `sortable` lets users disable the sorting and `fitContent` will remove the default width from a column so it fits the column content
I removed the flex layout from the table, it doesn't make sense
- #251 
- #252

feat(vue-data-table): add row to scoped slot; add sortable, fitContent

---

src/app/shared/components/VueButton/VueButton.spec.ts
src/app/shared/components/VueButton/VueButton.vue

Explicitly set the width of buttons, based on their actual initial width. This means that when you click a button & it goes into the loading state, it does not change width and appear to visually jump around on the page.

fix(vue-button): set fixed width for button loading

---

src/app/form/FormExample/FormExample.vue
src/app/shared/components/VueButton/VueButton.vue
src/app/shared/components/VueCheckbox/VueCheckbox.vue
src/app/shared/components/VueInput/VueInput.vue
src/app/shared/components/VueSelect/VueSelect.vue
src/app/shared/components/VueToggle/VueToggle.vue

closes #286
This PR disables the inheritance of attributes on input components that have a wrapper element.
I discovered an unwanted behavior when I applied tabIndex to input fields. because the tabIndex is not a prop of the input component it is handled as an attribute. Vue automatically adds attributes to the root element of a component, in this case, a `<div>`.
The right behavior is to have only one tabIndex in a component which is the Input component. I checked other components for the same error and fixed it.
I also added vee-validate to the checkbox and toggle component.
#286

refactor(components): remove attr from wrapper divs

---

src/app/shared/plugins/vuex-persist/PersistCookieStorage.ts
src/app/shared/plugins/vuex-persist/PersistLocalStorage.ts
src/app/shared/plugins/vuex-persist/vuex-persist.spec.ts
src/app/shared/plugins/vuex-persist/vuex-persist.ts
src/app/store.ts

closes #295
This PR adds an option `preferInitialState` to the vuex-persist Storage interface, this solves the use case described in #295 
@tamer-mohamed I think this is the right abstraction for this issue, please verify.
#295

feat(vuex-persist): add forceInitialState option

---

tools/scripts/Utils.spec.ts
tools/scripts/Utils.ts

closes #293
This PR will add the feature to `extract-i18n-messages` to parse translations that are in a single line condition. 
currently, this `{{ foo === 1 ? $t('foo' /* Foo */) : $t('bar' /* bar */) }}` 
extracts: `"foo": "Foo */) : $t('bar' /* bar"` 
with this PR it will extract: ```
"foo": "Foo",
"bar": "bar"```
it might not be the most scalable solution but should be good enough for now.
#293

feat(i18n): extract messages in single line conditions

---

tools/scripts/Utils.spec.ts
tools/scripts/Utils.ts

closes #301
This PR refactors the extract-i18n-messages script to handle the new prettier formatting. All tests for 
<div>
{{ $t('test' /* this is a test */) }}
{{ $t('test.test') }}
{{ foo === 1 ? $t('foo' /* Foo */) : $t('bar' /* bar */) }}
{{ $t('test.foo' /* test (test) [test] test */) }}
{{ $t('test.foo2' /* test (test) [test] test */) }}
{{ $t("test.bar" /* test (test) [test] test */) }}
<small>{{ $t('App.nav.counter' /* Counter */) }}</small>
text:  this.$t('components.register.submit.notification.text', model /* We've sent an email to: {email}! */),
$t('components.markdown' /*
- build on top of marked\n
- server side rendering!!!\n
- `github style` markdown
*/)
{{
$t(
'key',
{ key: value } /* key:
{key}? */,
)
}}      
</div>
are passing
nope 
#301

refactor(i18n): handle prettier formatting

---

.vue-starter/config.json
docs/tutorials/third-party.md
package-lock.json
package.json
src/app/app/App/App.vue

closes #328
This PR updates the vue-starter-service which now supports global css classes in the `global.scss` file.
I also simplified the access to 3rd party css and updated the vuetify docs.
@tamer-mohamed it's not completely what you described in your ticket, but this way we don't even need the global prefix.
#328

fix: use global css classes in global.scss

---

Dockerfile

the documentation says that vue-starter requires "Node.js >= 10"
just change the base image used to build the docker image
The documentation specifies that the required version of Node.js is 10+, better use ii during the build process

build: upgrade docker image to node:10

---

src/app/shared/components/VueButton/VueButton.spec.ts
src/app/shared/components/VueButton/VueButton.stories.ts
src/app/shared/components/VueButton/VueButton.vue
src/app/shared/designSystem/variables/_button.scss

This PR adds the ability to render a link as a button. supported link types:
- `router-link`
- `a`
@tamer-mohamed I decided against the generic solution because it ends up with a very ugly markup. The issue is that we have to dynamically bind props and attributes which can end up in a markup like this:
```
<router-link-stub event="click" to="/foo" as="router-link" class="button ripple"> </router-link-stub>
```
I had a look at vuetify, they also provide every single prop instead of a generic solution, should be fine.
no ticket

feat(vue-button): support link as button

---

.vuesion/config.json
package-lock.json
package.json

This PR adds the possibility to configure the watchOptions for the webpack dev-server. 
This is necessary because the current default values are causing trouble on windows machines, but they are like they are because another use-case of developing inside a docker container was solved with the current settings. 
My conclusion is to provide a configuration for it in order to enable both use cases without coming up with an abstraction.
not that I know.
no ticket

feat: add devServer watchOptions to vuesion cfg

---

src/app/shared/components/VueStarRating/VueStarRating.spec.ts
src/app/shared/components/VueStarRating/VueStarRating.stories.ts
src/app/shared/components/VueStarRating/VueStarRating.vue
src/app/shared/components/icons/VueIconStar/VueIconStar.vue
src/app/shared/designSystem/_variables.scss
src/app/shared/designSystem/docs/components/IconList.vue
src/app/shared/designSystem/variables/_star-rating.scss

Create new star rating component as suggested in: https://github.com/vuesion/vuesion/issues/192
WIP!
Need to add full test coverage & look at greater flexibility/customisability for the component

feat(components): add star rating

---

src/app/shared/components/VueSlider/VueSlider.spec.ts
src/app/shared/components/VueSlider/VueSlider.vue

closes #437
This PR fixes the issue that the focus indicator is not removed after move end
I used a setTimeout to solve the problem, might not be the most elegant solution
#437

fix(vue-slider): remove focus indicator after move end

---

src/app/shared/components/VueButton/VueButton.vue
src/app/shared/components/VueCheckbox/VueCheckbox.vue
src/app/shared/components/VueInput/VueInput.vue
src/app/shared/designSystem/variables/_button.scss
src/app/shared/designSystem/variables/_input.scss

closes #441
This PR aligns the input elements: input, checkbox, radio, and button. the checkbox is aligned in another PR
nope
#441

fix(components): align input elements

---

src/app/shared/components/VueCalendar/VueCalendar.spec.ts
src/app/shared/components/VueCalendar/VueCalendar.stories.ts
src/app/shared/components/VueCalendar/VueCalendar.vue

closes #471
This PR fixes a bug that appeared if the first day of the month is on a Sunday and the first day of the week is set to Monday. This resulted in a negative left padding which is now set to 6 (Sunday) if negative.
nope
#471

fix(vue-calendar): fix left padding for negative values

---

src/app/app.ts
src/app/router.ts
src/app/shared/services/HttpService/HttpService.ts
src/app/shared/testing/test-utils.ts
src/client/index.ts
src/server/isomorphic.ts
src/server/utils/Logger.ts

closes #350
This PR makes the lifecycle of `prefetch` more explicit. It now does fetch global data before the auth-guard is called, which fixes the problem described in #350. (not able to access prefetched data e.g. roles in the auth-guard)
This is only explicit for the AuthGuard that comes with vuesion, users could have problems with custom guards. Maybe, we can find a different abstraction in the future
#350

refactor(prefetch): call App.prefetch first, then AuthGuard

---

src/app/shared/components/VueCalendar/VueCalendar.spec.ts

changed assertion since VueCalendar's today property always initializes with current runtime date
after checking out the vuesion project, i faced a failed test. 
The test was providing a hard coded Date for today property but the component always initializes with the current runtime date. I think in this case should the test be updated.
i don't think so

test(calendar): corrected existing test

---

src/server/isomorphic.ts
src/server/utils/Logger.ts
src/server/utils/createLogger.ts

This fixes a memory leak with SSR. As we're running every request in a new V8 context, a new logger instance is created every time and is not properly cleaned up. We end up with huge amounts of open file handles for the log files and we get a warning from NodeJS about too many event listeners (`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limi`).
With the proposed change memory consumption is stable.
I was also looking into changing  the setting for SSR to not create a new context for every request but then memory consumption went up and up and never down again so it seems we have another leak that is just controlled by freeing up memory because of the separate …

Fix memory leak related to logging within server-side rendering
